version: '2'
services:
  registration:
    image: registration
  results:
    image: results
    depends_on:
      - kestrel
    environment:
      - SERVICE_LOCATION=HOSTNAME
  root:
    image: root
    ports:
      - "8080:8080"
    depends_on:
      - registration
      - results
      - kestrel
    environment:
      - SERVICE_LOCATION=HOSTNAME
  kestrel:
    image: kestrel

